apiVersion: v1
kind: Service
metadata:
  name: mongoserv-service
spec:
  ports:
  - port: 40
    targetPort: mongoserv-port
    protocol: TCP
  selector:
    app: mongoservice-backend
  type: LoadBalancer
