apiVersion: v1
kind: Service
metadata:
  name: mongoserver-service
spec:
  ports:
    #actual listening happens here
  - port: 4000
    nodePort: 31000
    protocol: TCP
  selector:
    app: mongoservice-backend
  type: NodePort
